spring:

  # DB 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://greenpingdb.co0xa4va8h7t.ap-northeast-2.rds.amazonaws.com:3306/greenPing?useUnicode=true&characterEncoding=utf8mb4
    username: admin
    password: greenping3226!
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
      show_sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect

springdoc:
  swagger-ui:
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
